wget http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Thin.woff2
wget http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Thin.woff
wget http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Thin.otf
wget http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Light.woff2
wget http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Light.woff
wget http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Light.otf
wget http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-DemiLight.woff2
wget http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-DemiLight.woff
wget http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-DemiLight.otf
wget http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Regular.woff2
wget http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Regular.woff
wget http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Regular.otf
wget http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Medium.woff2
wget http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Medium.woff
wget http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Medium.otf
wget http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Bold.woff2
wget http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Bold.woff
wget http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Bold.otf
wget http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Black.woff2
wget http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Black.woff
wget http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Black.otf
